import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import Baslik from "@/components/Baslik";
import CustomFooter from "@/components/CustomFooter";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mustafa Taşlıalan Web Sitesi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="tr">
      <body
        style={{ fontFamily: "'Times New Roman', serif" }}
        className="antialiased"
      >
        {/* Google Analytics kodları */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-WPLN4GS5XG"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-WPLN4GS5XG');
          `}
        </Script>

        <Baslik />
        {children}
        <CustomFooter />
      </body>
    </html>
  );
}





